spring:
  application:
    name: estudos
  datasource:
    dbcp2:
      validation-query: SELECT 1
      test-while-idle: 'true'
    hikari:
      connectionTimeout: '20000'
      maximumPoolSize: '5'
    password: postgre
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/usuarios
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    
server:
  port: 8080

          
    

