name: EstudosBackend
on:
  push:
    branches:
    - main
    - master

jobs:          
  build_and_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgre
          POSTGRES_DB: usuarios  # Nome do banco de dados
        # Configuração de health check
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432  # Expõe a porta do postgres
          
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        cache: maven
        distribution: 'temurin'

    - name: Build project with maven
      run: mvn --batch-mode -DskipTests package

    - name: Dependencies Cache
      uses: actions/cache@v3.4.2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Run Tests
      run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
